---
deployment:
  tasks:
    - export WEBROOT=/home/rlwrgzez/public_html
    - /bin/mkdir -p $WEBROOT/build
    - /bin/cp -R public/build/* $WEBROOT/build/ || true
    - /bin/cp -R public/brand $WEBROOT/ || true
    - /bin/cp public/robots.txt $WEBROOT/robots.txt || true
    - /bin/cp public/favicon.ico $WEBROOT/favicon.ico || true
