<?php

return [
    'plans' => [
        'free' => [
            'label' => 'Demo',
            'price' => 0,
            'billing_period' => 'luna',
            'description' => 'Demo standard pentru testare si evaluare rapida.',
            'project_limit' => 1,
            'users_limit' => 1,
            'stripe_price_id' => null,
            'features' => [
                'gantt' => false,
                'exports_csv' => false,
                'exports_enterprise' => false,
                'document_branding' => false,
            ],
        ],
        'start' => [
            'label' => 'Echipa Mica',
            'price' => 129,
            'price_yearly' => 1290,
            'billing_period' => 'luna',
            'description' => 'Pentru echipe mici care gestioneaza santiere de renovari sau amenajari.',
            'project_limit' => 2,
            'users_limit' => 3,
            'stripe_price_id' => env('STRIPE_PRICE_START'),
            'stripe_price_id_yearly' => env('STRIPE_PRICE_START_YEARLY'),
            'features' => [
                'gantt' => false,
                'exports_csv' => false,
                'exports_enterprise' => false,
                'document_branding' => false,
            ],
        ],
        'pro' => [
            'label' => 'Brand complet',
            'price' => 250,
            'price_yearly' => 2500,
            'billing_period' => 'luna',
            'description' => 'Brand complet: logo, culori, antet, footer si template-uri de documente.',
            'project_limit' => null,
            'users_limit' => 10,
            'stripe_price_id' => env('STRIPE_PRICE_PRO'),
            'stripe_price_id_yearly' => env('STRIPE_PRICE_PRO_YEARLY'),
            'features' => [
                'gantt' => true,
                'exports_csv' => true,
                'exports_enterprise' => true,
                'document_branding' => true,
                'document_templates' => true,
                'document_footer' => true,
            ],
        ],
        'enterprise' => [
            'label' => 'Enterprise',
            'price' => 999,
            'price_yearly' => 9990,
            'billing_period' => 'luna',
            'description' => 'Mai multe sabloane, aprobari, white-label si domeniu propriu.',
            'project_limit' => null,
            'users_limit' => null,
            'stripe_price_id' => env('STRIPE_PRICE_ENTERPRISE'),
            'stripe_price_id_yearly' => env('STRIPE_PRICE_ENTERPRISE_YEARLY'),
            'features' => [
                'gantt' => true,
                'exports_csv' => true,
                'exports_enterprise' => true,
                'document_branding' => true,
                'document_templates' => true,
                'document_approvals' => true,
                'white_label' => true,
                'custom_domain' => true,
            ],
        ],
    ],
];
