<?php

return [
    'canonical' => [
        [
            'id' => 'apartment_2_rooms',
            'name' => 'Apartament 2 camere',
            'project_type' => 'apartment_2_rooms',
            'complexity_factor' => 1.0,
            'template_payload' => [
                'project_type' => 'apartment_2_rooms',
                'title' => 'Oferta renovare apartament 2 camere',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 14,
                'package_tier' => 'standard',
                'smart_inputs' => ['walls_area' => 55, 'floor_area' => 42, 'tile_area' => 18, 'outlets_count' => 18, 'lights_count' => 12, 'doors_count' => 5],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 450],
                    ['label' => 'Consumabile', 'amount' => 350],
                    ['label' => 'Management proiect', 'amount' => 700],
                ],
                'optional_features' => [
                    ['key' => 'parchet_premium', 'label' => 'Parchet premium', 'enabled' => false, 'amount' => 1600],
                    ['key' => 'spoturi_led', 'label' => 'Spoturi LED', 'enabled' => true, 'amount' => 900],
                ],
                'stages' => [
                    ['name' => 'Demolare', 'duration_days' => 2, 'items' => []],
                    ['name' => 'Instalatii electrice', 'duration_days' => 2, 'items' => []],
                    ['name' => 'Instalatii sanitare', 'duration_days' => 2, 'items' => []],
                    ['name' => 'Tencuieli', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Glet + vopsitorie', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Pardoseli', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 1, 'items' => []],
                ],
            ],
        ],
        [
            'id' => 'apartment_3_rooms',
            'name' => 'Apartament 3 camere',
            'project_type' => 'apartment_3_rooms',
            'complexity_factor' => 1.1,
            'template_payload' => [
                'project_type' => 'apartment_3_rooms',
                'title' => 'Oferta renovare apartament 3 camere',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 15,
                'package_tier' => 'premium',
                'smart_inputs' => ['walls_area' => 75, 'floor_area' => 58, 'tile_area' => 24, 'outlets_count' => 26, 'lights_count' => 17, 'doors_count' => 7],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 600],
                    ['label' => 'Consumabile', 'amount' => 500],
                    ['label' => 'Protectii', 'amount' => 450],
                    ['label' => 'Management proiect', 'amount' => 1100],
                ],
                'optional_features' => [
                    ['key' => 'parchet_premium', 'label' => 'Parchet premium', 'enabled' => true, 'amount' => 2300],
                    ['key' => 'spoturi_led', 'label' => 'Spoturi LED', 'enabled' => true, 'amount' => 1400],
                    ['key' => 'mobilier_bucatarie', 'label' => 'Mobilier bucatarie', 'enabled' => false, 'amount' => 4500],
                ],
                'stages' => [
                    ['name' => 'Demolare', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Instalatii electrice', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Instalatii sanitare', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Tencuieli', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Glet + vopsitorie', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Pardoseli', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Bai', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Bucatarie', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 1, 'items' => []],
                ],
            ],
        ],
        [
            'id' => 'house',
            'name' => 'Casa',
            'project_type' => 'house',
            'complexity_factor' => 1.3,
            'template_payload' => [
                'project_type' => 'house',
                'title' => 'Oferta renovare casa',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 19,
                'package_tier' => 'premium',
                'smart_inputs' => ['walls_area' => 180, 'floor_area' => 120, 'tile_area' => 45, 'outlets_count' => 44, 'lights_count' => 34, 'doors_count' => 14],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 1600],
                    ['label' => 'Consumabile', 'amount' => 1300],
                    ['label' => 'Protectii', 'amount' => 900],
                    ['label' => 'Taxe', 'amount' => 700],
                    ['label' => 'Management proiect', 'amount' => 3200],
                ],
                'optional_features' => [
                    ['key' => 'parchet_premium', 'label' => 'Parchet premium', 'enabled' => true, 'amount' => 5400],
                    ['key' => 'sanitare_premium', 'label' => 'Obiecte sanitare premium', 'enabled' => true, 'amount' => 4800],
                    ['key' => 'usi_mdf_lemn', 'label' => 'Usi MDF vs lemn', 'enabled' => true, 'amount' => 4200],
                ],
                'stages' => [
                    ['name' => 'Demolare', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Instalatii electrice', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Instalatii sanitare', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Tencuieli', 'duration_days' => 7, 'items' => []],
                    ['name' => 'Glet + vopsitorie', 'duration_days' => 8, 'items' => []],
                    ['name' => 'Pardoseli', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Termoizolatie', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Fatada', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Acoperis', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Curte', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 2, 'items' => []],
                ],
            ],
        ],
        [
            'id' => 'commercial_space',
            'name' => 'Spatiu comercial',
            'project_type' => 'commercial_space',
            'complexity_factor' => 1.35,
            'template_payload' => [
                'project_type' => 'commercial_space',
                'title' => 'Oferta amenajare spatiu comercial',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 22,
                'package_tier' => 'luxury',
                'smart_inputs' => ['walls_area' => 210, 'floor_area' => 180, 'tile_area' => 30, 'outlets_count' => 60, 'lights_count' => 54, 'doors_count' => 8],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 1800],
                    ['label' => 'Consumabile', 'amount' => 1500],
                    ['label' => 'Protectii', 'amount' => 1200],
                    ['label' => 'Taxe', 'amount' => 950],
                    ['label' => 'Management proiect', 'amount' => 4200],
                ],
                'optional_features' => [
                    ['key' => 'spoturi_led', 'label' => 'Spoturi LED', 'enabled' => true, 'amount' => 3600],
                    ['key' => 'mobilier_bucatarie', 'label' => 'Mobilier bucatarie', 'enabled' => false, 'amount' => 0],
                ],
                'stages' => [
                    ['name' => 'Demolari masive', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Instalatii electrice industriale', 'duration_days' => 8, 'items' => []],
                    ['name' => 'Instalatii sanitare', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Tencuieli', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Pardoseli speciale', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Iluminat comercial', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Finisaje finale', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 2, 'items' => []],
                ],
            ],
        ],
        [
            'id' => 'full_renovation',
            'name' => 'Renovare completa',
            'project_type' => 'full_renovation',
            'complexity_factor' => 1.2,
            'template_payload' => [
                'project_type' => 'full_renovation',
                'title' => 'Oferta renovare completa',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 18,
                'package_tier' => 'premium',
                'smart_inputs' => ['walls_area' => 95, 'floor_area' => 70, 'tile_area' => 30, 'outlets_count' => 28, 'lights_count' => 20, 'doors_count' => 8],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 900],
                    ['label' => 'Consumabile', 'amount' => 750],
                    ['label' => 'Management proiect', 'amount' => 1800],
                ],
                'optional_features' => [
                    ['key' => 'parchet_premium', 'label' => 'Parchet premium', 'enabled' => false, 'amount' => 2800],
                    ['key' => 'sanitare_premium', 'label' => 'Obiecte sanitare premium', 'enabled' => false, 'amount' => 2200],
                    ['key' => 'spoturi_led', 'label' => 'Spoturi LED', 'enabled' => true, 'amount' => 1300],
                ],
                'stages' => [
                    ['name' => 'Demolare', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Instalatii electrice', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Instalatii sanitare', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Tencuieli', 'duration_days' => 5, 'items' => []],
                    ['name' => 'Glet + vopsitorie', 'duration_days' => 6, 'items' => []],
                    ['name' => 'Pardoseli', 'duration_days' => 4, 'items' => []],
                    ['name' => 'Usi', 'duration_days' => 3, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 2, 'items' => []],
                ],
            ],
        ],
        [
            'id' => 'partial_renovation',
            'name' => 'Renovare partiala',
            'project_type' => 'partial_renovation',
            'complexity_factor' => 0.9,
            'template_payload' => [
                'project_type' => 'partial_renovation',
                'title' => 'Oferta renovare partiala',
                'discount_pct' => 0,
                'tva_pct' => 21,
                'min_margin_pct' => 12,
                'package_tier' => 'standard',
                'smart_inputs' => ['walls_area' => 35, 'floor_area' => 24, 'tile_area' => 10, 'outlets_count' => 10, 'lights_count' => 8, 'doors_count' => 3],
                'indirect_costs' => [
                    ['label' => 'Transport', 'amount' => 250],
                    ['label' => 'Consumabile', 'amount' => 180],
                    ['label' => 'Management proiect', 'amount' => 450],
                ],
                'optional_features' => [
                    ['key' => 'spoturi_led', 'label' => 'Spoturi LED', 'enabled' => false, 'amount' => 500],
                ],
                'stages' => [
                    ['name' => 'Demolare', 'duration_days' => 1, 'items' => []],
                    ['name' => 'Instalatii electrice', 'duration_days' => 1, 'items' => []],
                    ['name' => 'Glet + vopsitorie', 'duration_days' => 2, 'items' => []],
                    ['name' => 'Pardoseli', 'duration_days' => 2, 'items' => []],
                    ['name' => 'Curatenie finala', 'duration_days' => 1, 'items' => []],
                ],
            ],
        ],
    ],
];
